In [1]:
from OpenAICall import OpenAICall

model="gpt-4-gizmo-g-pmuQfob8d"

system_prompt = "You are a helpful assistant."
user_prompt = "Compose a poem that explains the concept of recursion in programming."
messages=[
        {
            "role": "system",
            "content": system_prompt,
        },
        {
            "role": "user",
            "content": user_prompt,
        },
    ]
temperature=1

response = OpenAICall(messages, model, temperature)

# 打印返回的消息内容
print("Response from OpenAI:")
print(response)

Response from OpenAI:
In the heart of code, where logic sways,
Recursion dances through the maze.
A function calls itself, you see,
In a loop of infinity.

With each call, a task anew,
Solving bits, both large and few.
Step by step, it breaks the chain,
Till base case clears the main.

Like a mirror within a mirror’s view,
Or endless halls where echoes flew,
It simplifies the grandest scheme,
A dream within a coder’s dream.

But beware the endless call,
A loop that never ends at all.
Set your base case firm and clear,
To guide it home, to reappear.

Recursion, elegant and grand,
In the world of code, it takes its stand.
A loop that binds, a loop that frees,
The art of endless possibilities.

In [2]:
import os
import pandas as pd

directory='../Data/Internal Metrics'
name2path={}
file_dict={}
data_schema=[]
for file in os.listdir(directory):
      if file.endswith('.csv'):
            group = file.split('(')[0].strip()
            file_name = file.split('(')[1].split(')')[0].strip()

            file_path=os.path.join(directory, file)
            df=pd.read_csv(file_path)
            
            data_schema.append(
                  {
                        'Group':group,
                        'file_name':file_name,
                        'Column': df.columns,
                        'First_Row':str(df.iloc[0]),
                        'Second_Row':str(df.iloc[1]),
                        'Data_Type': str(df.dtypes), 
                  }
            )

            name2path[file_name]=file_path

In [16]:
DataSchema=pd.DataFrame(data_schema).sort_values(by=['Group','file_name']).reset_index(drop=True)
DataSchema.head(5)

,Group,file_name,Column,First_Row,Second_Row,Data_Type
0,Android,Android Device Distribution,"Index(['Device', 'Count'], dtype='object')",Device LGE Nexus 4\nCount 216\n...,Device asus Nexus 7\nCount 183...,Device object\nCount int64\ndtype: object
1,Android,Android Device Distribution - Past 2 Weeks,"Index(['Device', 'Count'], dtype='object')",Device LGE Nexus 4\nCount 149\n...,Device asus Nexus 7\nCount 144...,Device object\nCount int64\ndtype: object
2,Android,Android Version Distribution,"Index(['Version', 'Count'], dtype='object')","Version 4.3\nCount 625.0\nName: 0, d...","Version 4.1\nCount 584.0\nName: 1, d...",Version float64\nCount int64\ndtype:...
3,Android,Android Version Distribution - Past 2 weeks,"Index(['Version', 'Count'], dtype='object')","Version 4.3\nCount 466.0\nName: 0, d...","Version 4.1\nCount 445.0\nName: 1, d...",Version float64\nCount int64\ndtype:...
4,Android,App Version Distribution - Past 2 Weeks,"Index(['Device', 'Count'], dtype='object')","Device 1.0.2 \nCount 1357\nName: 0, d...","Device 1.0 \nCount 4\nName: 1, dtype...",Device object\nCount int64\ndtype: object

In [17]:
DataSchema[DataSchema['Group']=='Bonus']

,Group,file_name,Column,First_Row,Second_Row,Data_Type
9,Bonus,Bonus Popularity,"Index(['Bonus', 'Count'], dtype='object')",Bonus mobile-app\nCount 26990\nName...,Bonus desktop-uploader\nCount ...,Bonus object\nCount int64\ndtype: object
10,Bonus,Free Users Granted Bonus Months,"Index(['Percentile', 'Months'], dtype='object')",Percentile 0.05\nMonths 0.00\nName: ...,"Percentile 0.1\nMonths 0.0\nName: 1,...",Percentile float64\nMonths float64\n...
11,Bonus,Inviter Percentage by Cohort,"Index(['Week', 'Ratio'], dtype='object')",Week 2012-08-27\nRatio 0.0313\nName...,Week 2012-09-03\nRatio 0.0147\nName...,Week object\nRatio float64\ndtype: object
12,Bonus,Inviters by Cohort,"Index(['Week', 'Total Users', 'Inviters'], dty...",Week 2012-08-27\nTotal Users ...,Week 2012-09-03\nTotal Users ...,Week object\nTotal Users int64\n...
13,Bonus,"Inviters, Invites, Referral Bonuses per Invite...","Index(['Week', 'Inviters', 'Invites Sent', 'Re...",Week 2012-09-03\nInviter...,Week 2012-09-10\nInviter...,Week object\nInviters ...
14,Bonus,Invites per Inviter by Inviter Cohort,"Index(['Week', 'Invites Sent', 'Referral Bonus...",Week 2012-09-03\nInvites...,Week 2012-09-10\nInvites...,Week object\nInvites Se...
15,Bonus,Mac & Windows Uploader Connection Rate by User...,"Index(['Week', 'All Users', 'Invited', 'Photo ...",Week 2013-01-28\nAll User...,Week 2013-02-04\nAll User...,Week object\nAll Users ...
16,Bonus,Referred Invite Conversion Rates by Invite Tim...,"Index(['Week', '% Signed up', '% Earned Referr...",Week 2013-04-22\...,Week 2013-04-29\...,Week object\n% ...

In [13]:
from sqlalchemy import create_engine

# PostgreSQL数据库连接信息
username = 'tanghao'
password = ''
host = 'localhost'
port = '5432'
database = 'postgres'

# 创建连接引擎
engine = create_engine(f'postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}')

In [14]:
import pandas as pd

file_path='/Users/tanghao/NUS/Internship/EverpixAnalysis/Data/External Metrics/Old Flurry Metrics.csv'
file='Old Flurry Metrics'
df = pd.read_csv(file_path)
df.to_sql(file, engine, if_exists='replace', index=False)

365

In [ ]:
import psycopg2
import csv

# 连接到 PostgreSQL 数据库
conn = psycopg2.connect(
    dbname="postgres",
    user="tanghao",
    password="",
    host="localhost",
    port="5432"
)

# 创建游标
cur = conn.cursor()

# 创建表的 SQL 语句
create_table_sql = """
CREATE TABLE employees (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100),
    position VARCHAR(50),
    salary NUMERIC(10, 2),
    hire_date DATE
);
"""

# 执行创建表的 SQL 语句
cur.execute(create_table_sql)

# 提交事务
conn.commit()

# 导入 CSV 数据的函数
def import_csv_to_db(csv_file_path):
    with open(csv_file_path, 'r') as f:
        reader = csv.reader(f)
        next(reader)  # 跳过表头
        for row in reader:
            cur.execute(
                "INSERT INTO employees (id, name, position, salary, hire_date) VALUES (%s, %s, %s, %s, %s)",
                row
            )

# 调用导入 CSV 数据的函数
import_csv_to_db('/absolute/path/to/your/file.csv')

# 提交事务
conn.commit()

# 查询数据的 SQL 语句
select_all_sql = "SELECT * FROM employees;"

# 执行查询的 SQL 语句
cur.execute(select_all_sql)

# 获取查询结果
rows = cur.fetchall()

# 打印查询结果
for row in rows:
    print(row)

# 关闭游标和连接
cur.close()
conn.close()

### Archive

import pandas as pd
import os

# 假设文件夹路径为 'folder_path'
folder_path = '/Users/tanghao/NUS/Internship/EverpixAnalysis/Data/Internal Metrics'

# 初始化一个两层字典
file_summary_dict = {}
main_key_list=[]

# 遍历文件夹中的所有文件
for filename in os.listdir(folder_path):
    if filename.endswith('.csv'):
        # 提取文件名前后部分
        main_key, sub_key = filename.split('(')
        sub_key = sub_key.rstrip(').csv')
        main_key = main_key.strip()

        # 读取CSV文件
        file_path = os.path.join(folder_path, filename)
        df = pd.read_csv(file_path)
        
        # 创建DataFrame简介信息
        # df_summary = pd.DataFrame({
        #     'Column': df.columns,
        #     'Non-Null Count': df.notnull().sum(),
        #     'Data Type': df.dtypes,
        #     'Unique Count': df.nunique()
        # })
        
        # 将简介信息添加到字典中
        if main_key not in file_summary_dict:
            main_key_list.append(main_key)
            # file_summary_dict[main_key] = {}
            file_summary_dict[main_key] = []

        file_summary_dict[main_key].append(
            {
                'name':sub_key,
                'Column':df.columns()
            }
        )

# 示例输出
# for main_key, sub_dict in file_summary_dict.items():
#     print(f"Main Key: {main_key}")
#     for sub_key, summary in sub_dict.items():
#         print(f"  Sub Key: {sub_key}")
#         print(summary)